"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
const inter = Inter({ subsets: ["latin"] });
import { TonConnectUIProvider } from '@tonconnect/ui-react';
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <TonConnectUIProvider manifestUrl="https://tele-app-three.vercel.app//tonconnect-manifest.json">
        <Header/>
        {children}
        </TonConnectUIProvider> 
        </body>
    </html>
  );
}
